name: Deploy production site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy production
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          destination_dir: docs
          keep_files: true
          commit_message: 'Deploy production site for'
          enable_jekyll: true # Workaround for https://github.com/peaceiris/actions-gh-pages/issues/1131
